[project]
name = "flask-jwt-oops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SaquibAnjum", email = "saquib1312@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-jwt-extended>=4.7.4",
    "requests>=2.34.2",
]

[project.scripts]
flask-jwt-oops = "flask_jwt_oops:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
